FROM python:3.8-alpine3.11

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY test_requirements.txt /app
RUN pip install -r test_requirements.txt

ENV PYTHONUNBUFFERED=1

ENTRYPOINT nosetests
